---
services:
  spirit:
    container_name: spirit
    image: 'spacebinorg/spirit:v0.1.7a'
    restart: unless-stopped
    ports:
      - 9003:9000
  pulsar:
    container_name: pulsar
    environment:
      - PULSAR_INSTANCE=${INSTANCE}
    image: 'spacebinorg/pulsar:v1.1.3'
    ports:
      - 9002:3000
    depends_on:
      - spirit