services:
  mc:
    container_name: mc
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      SPIGET_RESOURCES: 9089,18494
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    restart: unless-stopped
    volumes:
      - /media/syn/docker/minecraft/data:/data
  rcon:
    container_name: rcon
    environment:
      RWA_PASSWORD: 1593
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: minecraft
    image: itzg/rcon
    ports:
      - 4326:4326
      - 4327:4327
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /opt/rcon-web-admin/db